/*
given two strings s and t, string t is generated by random shuffling
string s and then add one more letter at a random position
return the letter that was added to t

-intuition: hashmap, hashset
-another way: use the sume and then minus the
previous one, and then return the char
*/
#include <iostream>
#include <string>
using namespace std;

char findTheDifference(string s, string t){
    long sum = 0;
    for (size_t i = 0; i < s.size(); ++i){
        sum += (int)s[i];
    }
    for (size_t i = 0; i < t.size(); ++i){
        sum -= (int)t[i];
    }
    return (char)(-sum);
}

int main(){
    cout << findTheDifference("abcd","abcde") << endl;
}